# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edge_entropy_cpp <- function(image, impath = "image", maxdiag = 500L, gabor_bins = 24L, filter_length = 31L, circ_bins = 48L, rangesSEXP = NULL) {
    .Call(`_imfeatures_edge_entropy_cpp`, image, impath, maxdiag, gabor_bins, filter_length, circ_bins, rangesSEXP)
}

